local map = vim.keymap.set

-- Window navigation
map("n", "<C-h>", "<C-w>h", { desc = "Left window" })
map("n", "<C-j>", "<C-w>j", { desc = "Down window" })
map("n", "<C-k>", "<C-w>k", { desc = "Up window" })
map("n", "<C-l>", "<C-w>l", { desc = "Right window" })

-- File / search
map("n", "<leader>e", function()
	Snacks.explorer()
end, { desc = "Explorer" })
map("n", "<leader>ff", function()
	Snacks.picker.files()
end, { desc = "Find files" })
map("n", "<leader>fg", function()
	Snacks.picker.grep()
end, { desc = "Grep" })
map("n", "<leader>fr", function()
	Snacks.picker.recent()
end, { desc = "Recent files" })
map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics" })

-- Terminal
map("n", "<leader>tp", function()
	Snacks.terminal()
end, { desc = "Terminal popup" })

-- Test (neotest)
map("n", "<leader>tt", function()
	require("neotest").run.run()
end, { desc = "Run nearest test" })
map("n", "<leader>tf", function()
	require("neotest").run.run(vim.fn.expand("%"))
end, { desc = "Run file tests" })
map("n", "<leader>ts", function()
	require("neotest").summary.toggle()
end, { desc = "Toggle test summary" })
map("n", "<leader>to", function()
	require("neotest").output.open({ enter = true })
end, { desc = "Open test output" })

-- Debug (DAP)
map("n", "<leader>db", function()
	require("dap").toggle_breakpoint()
end, { desc = "Toggle breakpoint" })
map("n", "<leader>dB", function()
	require("dap").set_breakpoint(vim.fn.input("Condition: "))
end, { desc = "Conditional breakpoint" })
map("n", "<leader>dc", function()
	require("dap").continue()
end, { desc = "Continue" })
map("n", "<leader>di", function()
	require("dap").step_into()
end, { desc = "Step into" })
map("n", "<leader>do", function()
	require("dap").step_over()
end, { desc = "Step over" })
map("n", "<leader>dO", function()
	require("dap").step_out()
end, { desc = "Step out" })
map("n", "<leader>dr", function()
	require("dap").repl.toggle()
end, { desc = "DAP REPL" })
map("n", "<leader>du", function()
	require("dapui").toggle()
end, { desc = "DAP UI" })

-- Insert mode
map("i", "jj", "<Esc>", { desc = "Escape insert mode" })
